@startuml
'https://plantuml.com/class-diagram

class "회원" as member {
  id
  ---
  SNS 이메일 [인증과 연동, 변경 불가]
  상태 [회원, 탈퇴]
  생성 일시
  생성 id
  수정 일시
  수정 id
}

class "로그인 기록" as loginHistory {
  id
  ---
  회원 id
  인증 타입
  SNS 이메일
  로그인 ip
  상태 [성공, 실패]
  생성 일시
  생성 id
}

class "인증" as auth {
  회원 번호
  인증 타입[KAKAO, GOOGLE, NAVER]
  ---
  리프레시 토큰
  SNS 이메일
  생성 일시
  생성 id
  수정 일시
  수정 id
}

class "인증 기록" as authHistory {
  id
  ---
  회원 번호
  인증 타입
  SNS 이메일
  상태 [성공, 실패]
  생성 일시
  생성 id
}

@enduml