branchName: 'issue-${issue.number}'
autoLinkIssue: true
autoCloseIssue: true
autoDeleteBranch: true
#gitSafeReplacementChar: '-'
branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
  - label: documentation
    prefix: docs/