@startuml
autonumber
=== 이메일 인증 번호 요청 ==
"이메일 도메인" -> "인증 도메인": 인증 번호 생성 요청
"인증 도메인" -> "인증 도메인": 인증 번호 생성
"인증 도메인" -> redis: 인증 번호 임시 저장(만료 10분)
"인증 도메인" -> "이메일 도메인": 인증 번호 전송

=== 인증 번호 검증 ==
"이메일 도메인" -> "인증 도메인": 이메일 + 인증 번호 검증 요청
"인증 도메인" -> redis: 이메일 기준 인증 번호 조회
"인증 도메인" -> "인증 도메인": 인증 번호 검증
alt
  group 인증 실패
  "인증 도메인" -> "이메일 도메인": 인증 예외 응답
end
"인증 도메인" -> "이메일 도메인": 인증 성공 응답

@enduml