spring:
  devtools:
    livereload:
      enabled: true
  jackson:
    time-zone: "UTC"
  datasource:
    url: jdbc:mysql://localhost:13306/boot2_hexagonal?characterEncoding=utf-8&serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
      idle-timeout: 30000
    username: boot2
    password: p@ssw0rd
  jpa:
    database: mysql
    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
  redis:
    host: localhost
    port: 16379
    password: p@ssw0rd

logging:
  level:
    root: debug
server:
  error:
    include-stacktrace: always
    include-exception: true
    include-binding-errors: always

smtp:
  host: smtp.naver.com
  port: 465
  username: idean3885
  sender: ${smtp.username}@naver.com
