spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  redis:
    host: localhost
    port: 6380
#    port: ${random.int[10000,65536]}
    password:

server:
  error:
    include-stacktrace: always
    include-exception: true
    include-binding-errors: always
