@startuml
'https://plantuml.com/sequence-diagram

actor "사용자" as user
participant "인증" as auth
participant "OAuth 서버" as oauth
participant "회원" as member
participant "DB" as db

autonumber

=== 로그인 ==
user -> auth: SNS 로그인 요청
auth -> oauth: 인가 토큰 요청
user <-- oauth: SNS 로그인 요청
user -> oauth: SNS 로그인 전달
user <-- oauth: 인증 토큰 + 리다이렉트 url 응답
user -> auth: 토큰 발급 요청
auth -> oauth: 토큰 발급 요청
auth <-- oauth: 토큰 전달

auth -> db: 기존 인증 조회
alt 인증 조회됨.
  auth -> db: 인증 정보 수정
else 미존재
  auth -> member: 회원 가입 요청
  member -> member: 가입 처리
  member -> db: 회원 정보 생성
  auth <-- member: 회원 정보 응답
  auth -> db: 인증 정보 생성(+ 회원 번호)
end
auth -> db: 인증 기록 생성
auth -> db: 로그인 기록 생성
auth -> auth: 인가 토큰 생성
user <-- auth: 인가 토큰 응답

@enduml