@startuml
'https://plantuml.com/use-case-diagram

title Infra Architecture

actor developer

package docker as docker {
  (registry) as registry
}

package argocd as argocd {
  (application) as application
}

package GitHub as GitHub {
  package githubAction as githubAction {
    (code build) as codeBuild
    (image create) as imageCreate
    (chart create) as chartCreate
  }
}

GitHub <- developer: code push
GitHub -> githubAction: trigger
codeBuild -> imageCreate
imageCreate -> registry: push image
imageCreate -> chartCreate
chartCreate --> registry: push chart
registry <. application: Chart & Image pull

@enduml