version: '3.4'

services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=boot2
      - MYSQL_PASSWORD=p@ssw0rd
      - MYSQL_DATABASE=boot2_hexagonal
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --bind-address=0.0.0.0
    cap_add:
      - SYS_NICE
    ports:
      - "13306:3306"
    networks:
      - boot2
  redis:
    image: redis:7.0-alpine

    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "16379:6379"
    command: redis-server --requirepass p@ssw0rd
    networks:
      - boot2
networks:
  boot2:
    driver: bridge
