@startuml
autonumber
=== 이메일 인증 번호 요청 ==
사용자 -> "서버 도메인": 이메일 인증 번호 요청
"서버 도메인" -> "이메일 도메인": 이메일 인증 번호 요청
"이메일 도메인" -> "사용자 이메일": 인증 번호 전송
"이메일 도메인" -> "서버 도메인": 인증 번호 요청 결과
"서버 도메인" -> 사용자: 인증 번호 요청 결과

autonumber
=== 회원 가입 ==
사용자 -> "서버 도메인": 가입 요청
"서버 도메인" -> "회원 도메인": 회원 가입 요청
"회원 도메인" -> "이메일 도메인": 이메일 인증 확인 요청
"이메일 도메인" -> "이메일 도메인": 이메일 인증 확인 처리
"이메일 도메인" -> "회원 도메인": 이메일 인증 확인 결과
"회원 도메인" -> "회원 도메인": 회원 가입 처리
"회원 도메인" -> "서버 도메인": 회원 가입 처리 결과
"서버 도메인" -> 사용자: 회원 가입 처리 결과
@enduml