@startuml

actor 사용자

package "이메일 도메인" {
  (이메일 전송)
}

package "이메일 발송 내역" {
    (발송 내역 저장)
}

rectangle "사용자 이메일" {
  (수신함)
}

package "회원 도메인" {
  (회원 가입)
}

package "인증 도메인" {
  (이메일 인증 번호 요청)
  (이메일 유효성 검증)
  ([TBD]sns 인증 번호 요청)
}

(수신함) <- (이메일 전송)
사용자 -> (이메일 인증 번호 요청)
사용자 -> (이메일 유효성 검증)
(이메일 인증 번호 요청) --> (이메일 전송): 전송 요청
(이메일 전송) --> (발송 내역 저장)

사용자 --> (회원 가입): 인증 번호 포함하여 회원 가입 요청
(회원 가입) --> (이메일 유효성 검증): 이메일 인증 요청
@enduml