email:
  format:
    request-authentication-code:
      subject: Send Authentication Code
      body: |
        <!DOCTYPE html>
        <html>
        <head>
        <style>
        h1 {
          color: white;
          text-align: center;
        }
        </style>
        </head>
        <div style="background-color: lightblue;">
        <h1>인증 코드 전송</h1>
        인증 코드는 
        <span style="color: blue; font-size: 30px; user-select: all">${authenticationCode}</span>
        입니다.
  
        </div>
        </html>