@startuml
autonumber
=== 회원 가입(via. 이메일) ==
사용자 -> "회원 도메인": 회원 가입 요청
"회원 도메인" -> "이메일 도메인": 이메일 검증 요청
"이메일 도메인" -> "회원 도메인": 이메일 검증 결과
alt 검증 실패
  "회원 도메인" -> 사용자: 이메일 검증 실패
end
"회원 도메인" -> "회원 도메인": 회원 가입 처리
"회원 도메인" -> 사용자: 회원 가입 결과
@enduml