@startuml

actor 사용자

package "회원 도메인" as member {
  (회원 가입)
'  ([TBD]sns 인증 코드 요청)
}

package "이메일 도메인" as email {
  (이메일 인증 코드 요청)
  (이메일 유효성 검증)
}

사용자 -> (이메일 인증 코드 요청)
사용자 -> (이메일 유효성 검증)

사용자 --> (회원 가입): 인증 코드 포함하여 회원 가입 요청
(회원 가입) --> (이메일 유효성 검증): 이메일 인증 요청
@enduml