@startuml
autonumber
=== 이메일 인증 코드 요청 ==
사용자 -> "이메일 도메인": 이메일 인증 코드 요청
"이메일 도메인" -> "인증 도메인": 인증 코드 생성 요청
"이메일 도메인" -> "사용자 이메일": 인증 코드 전송
"이메일 도메인" -> "이메일 전송 기록": 기록 저장
"이메일 도메인" -> 사용자: 인증 코드 요청 결과

=== 이메일 유효성 검증 ==
사용자 -> "이메일 도메인": 이메일 유효성 검증 요청(with 인증 코드)
"이메일 도메인" -> "인증 도메인": 인증 코드 검증 요청
alt
  group 인증 실패
  "인증 도메인" -> "이메일 도메인": 인증 예외 응답
  "이메일 도메인" -> 사용자: 인증 실패 응답
end
"이메일 도메인" -> 사용자: 인증 성공 응답
@enduml